[directory]
read_only = " "
truncation_length = 1

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "
format = 'via [$symbol]($style)'

[hg_branch]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "
format = 'via [$symbol]($style)'

[package]
symbol = " "

[python]
symbol = " "
format = 'via [$symbol]($style)'

[rust]
format = 'via [$symbol]($style)'

[git_status]
disabled = true

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_metrics]
disabled = false

