#!/bin/bash

TOOLTIP='Default Keybinds\n'\
'SUPER + ENTER = Start Alacritty\n'\
'SUPER + Q = Close Window\n'\
'SUPER + L = Lock Screen\n'\
'SUPER + M = Logout menu\n'\
'SUPER + E = File Manager\n'\
'SUPER + V = Toggle Float\n'\
'SUPER + SPACE = App Launcher\n'\
'SUPER + S = Screenshot\n'\
'SUPER + T = Switch HyprV version\n'\
'ALT + V = Open clipboard manager'

echo '{"tooltip": "'$TOOLTIP'"}'