#!/bin/bash

update_theme() {
    xfconf-query -c xsettings -p /Net/ThemeName -s "Catppuccin-Mocha-Standard-Mauve-Dark"
    gsettings set org.gnome.desktop.interface gtk-theme "Catppuccin-Mocha-Standard-Mauve-Dark"
}
restart_waybar() {
    #restart the waybar
    pkill waybar
    waybar
}

set_current_background() {
    swww img "/usr/share/sddm/themes/sdt/wallpaper.jpg"
}


set_current_background
update_theme
restart_waybar


# need to show the version and tooltip
VER="R"

TOOLTIP='Default Keybinds\n'\
'SUPER + Return = Start Kitty\n'\
'SUPER + F4 = Close Window\n'\
'SUPER + L = Lock Screen\n'\
'SUPER + M = Logout menu\n'\
'SUPER + E = File Manager\n'\
'SUPER + V = Toggle Float\n'\
'SUPER + SPACE = App Launcher\n'\
'SUPER + S = Screenshot\n'\
'SUPER + T = Switch HyprV version\n'\
'ALT + V = Open clipboard manager'

echo '{"text": "'$VER'", "tooltip": "'$TOOLTIP'"}'