format = """
[░▒▓](#E6E6FA)\
[  ](bg:#E6E6FA fg:#090c0c)\
[](bg:#E0B0FF fg:#E6E6FA)\
$directory\
[](fg:#E0B0FF bg:#CF9FFF)\
$git_branch\
$git_status\
[](fg:#CF9FFF bg:#CF9FFF)\
$nodejs\
$rust\
$golang\
[](fg:#CF9FFF)\
$time\
\n$character"""

[directory]
style = "fg:#51414F bg:#E0B0FF"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " "

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#483248"
format = '[[ $symbol $branch ](fg:#483248 bg:#CF9FFF)]($style)'

[git_status]
style = "bg:#AA336A"
format = '[[($all_status$ahead_behind )](fg:#AA336A bg:#CF9FFF)]($style)'

[nodejs]
symbol = ""
style = "bg:#483248"
format = '[[ $symbol ($version) ](fg:#483248 bg:#CF9FFF)]($style)'

[rust]
symbol = ""
style = "bg:#483248"
format = '[[ $symbol ($version) ](fg:#483248 bg:#CF9FFF)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#483248"
format = '[[ $symbol ($version) ](fg:#483248 bg:#CF9FFF)]($style)'

[time]
disabled = true
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#CF9FFF)]($style)'

[docker_context]
symbol = " "

[hg_branch]
symbol = " "

[memory_usage]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "
format = 'via [$symbol]($style)'

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[shell]
fish_indicator = ''
style = 'cyan bold'
disabled = false

[git_metrics]
disabled = false
